### ISSUE TITLE
Current Issues regarding new release

### ISSUE THREAD

**Issue by davidtrushkov** [davidtrushkov/marketplace#46]
These are the current issues I found when I pushed Marketplace to [marketplace.davidtrushkov.com](marketplace.davidtrushkov.com):

- [x] Spell error on about page.

- [x] Can't see the warning dialog when first time connecting to Stripe. 

- [x] Limit number of files user can upload in dropzone JS

- [x] Fix badge notification icon to `padding 2px 6px`

- [x] User avatar image not working on notification pages

- [x] Update the config/mail.php to match real environment variables 

- [x] Remove footer and body CSS positioning on mobile devices.

- [x] This issue happens when I click "Most Sales" in the filter bar on the files page:
`
SQLSTATE[42000]: Syntax error or access violation: 1055 'davidtru_marketplace.files.identifier' isn't in GROUP BY (SQL: select files.*, count(sales.id) AS count from `files` left join `sales` on `sales`.`file_id` = `files`.`id` where `finished` = 1 and `live` = 1 and `approved` = 1 and `files`.`deleted_at` is null group by `files`.`id` order by `count` desc limit 15 offset 0)
`

**Comment by huzairuje** [comment]
hei @davidtrushkov  i got an error go to admin dashboard like this
`Illuminate \ Database \ QueryException (42703)
SQLSTATE[42703]: Undefined column: 7 ERROR: column "%m/%d" does not exist LINE 1: select DATE_FORMAT(created_at, "%m/%d") as day, sum(sale_pri... ^ (SQL: select DATE_FORMAT(created_at, "%m/%d") as day, sum(sale_price) as sale_price from "sales" where "created_at" > 2018-03-01 00:00:00 and "sale_price" > 0 group by "day")` 
what can i do or can i contact your email ?

**Comment by davidtrushkov** [comment]
Did you clone this on your own computer, or are you having the error on my live website?

If you downloaded it to your computer, then are you by any chance using a database that is **not** MySQL, like sq-lite, or PostgreSQL? Because I had the same problem when I tried to upload to Heroku, I got the same error because the query im doing there can only work on MySQL database I believe. (Heroku doesn't use MySQL by default)

**Comment by huzairuje** [comment]
oh i see @davidtrushkov :+1: thank you. so i gotta use mysql ? okay i will try migrate again

**Comment by huzairuje** [comment]
one more @davidtrushkov where can i show all files ? updated files and new files ? or i can't see it ?

**Comment by davidtrushkov** [comment]
I have a section in the Admin dashboard where you can see new and updated files coming in from users. I don't have a section to list all the files with their uploads however.


________________________________
